[build]
  command = "npm run build"
  publish = "out"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "false"
  CI = "true"
  NEXT_PUBLIC_LOG_LEVEL = "debug"
